### ISSUE TITLE
Dev api not reachable

### ISSUE THREAD

**Issue by alpeshv** [loadimpact/loadimpact-docs#29]
Getting 'No such host' error for http://api.dev.loadimpact.com/v3/users while running an example from this page.

**Comment by markjmeier** [comment]
@alpeshv I assume you are reading this article: https://support.loadimpact.com/4.0/guides/how-to-load-test-a-restful-api/ . The dev API is just there an example/placeholder.  You should replace the with your own endpoint.  Alternatively, we have some endpoints set up here that can be used: http://httpbin.test.loadimpact.com/

**Comment by alpeshv** [comment]
@markjmeier thank you. The way it was given, it looked like a genuine endpoint from a sample api.

**Comment by markjmeier** [comment]
@alpeshv that makes sense - I'll make sure we notate that it should be replaced in the docs.  Thanks for raising the issue!
