### ISSUE TITLE
Error in the link of the code samples of parameterization

### ISSUE THREAD

**Issue by german-e-mas** [loadimpact/loadimpact-docs#35]
This issue is about <https://support.loadimpact.com/4.0/getting-started/create-first-test/> (source file: <https://github.com/loadimpact/loadimpact-docs/blob/master/jekyll/_v4/getting-started/create-first-test.md>)

In the [Common Questions section](https://support.loadimpact.com/4.0/getting-started/create-first-test/#common-questions), in the first parapgraph (I need to parameterize data from a JSON or CSV file, how do I do that?), the [code sample link](https://support.loadimpact.com/4.0//examples/parameterizing-data/) is wrong. Removing the extra slash before examples [fixes it](https://support.loadimpact.com/4.0/examples/parameterizing-data/).

Hope this helps.

**Comment by markjmeier** [comment]
@german-e-mas Thanks for catching this. I've fixed this now.
