### ISSUE TITLE
Setting cookies manually is wrong and not working 

### ISSUE THREAD

**Issue by Hack4Life** [loadimpact/loadimpact-docs#36]
This issue is about <https://support.loadimpact.com/3.0/user-scenarios-scripting-examples/how-are-cookies-handled/> (source file: <https://github.com/loadimpact/loadimpact-docs/blob/master/jekyll/_v3/user-scenarios-scripting-examples/how-are-cookies-handled.md>)

The way it is described via setting a header with

>  ["Cookie"]="timezone=Europe/Berlin"

will result in the following output if there is already a session set via cookie (session is handled automatically via LoadImpact):
![image](https://user-images.githubusercontent.com/11788789/65502251-ba2c5500-dec2-11e9-9a66-9c329da1ab51.png)

This is the wy it should look like: 
![image](https://user-images.githubusercontent.com/11788789/65502365-f1026b00-dec2-11e9-8011-888021ec450c.png)

**Comment by markjmeier** [comment]
@Hack4Life Hey there - I see you sent a note into support on this.  This is actually a bug in v3.0 and has been reported to our team.  In the meantime, as mentioned in the reply, we would recommend building your test out in v4.0 if possible.
